CREATE TABLE Player
(playerID DECIMAL(10,0) NOT NULL,
 name VARCHAR(256) NOT NULL,
 team VARCHAR(256) NOT NULL,
 PRIMARY KEY (playerID));

CREATE TABLE FantasyTeam
(teamID DECIMAL(10,0) NOT NULL,
 name VARCHAR(256) NOT NULL,
 wins INTEGER NOT NULL,
 losses INTEGER NOT NULL,
 PRIMARY KEY (teamID));

CREATE TABLE User
(userID DECIMAL(10,0) NOT NULL,
 username VARCHAR(256) NOT NULL,
 password VARCHAR(256) NOT NULL,
 PRIMARY KEY (userID));

CREATE TABLE Game
(gameID DECIMAL(10,0) NOT NULL,
 week INTEGER NOT NULL,
 PRIMARY KEY (gameID));

CREATE TABLE FantasyGame
(fantasygameID DECIMAL(10,0) NOT NULL,
 week INTEGER NOT NULL,
 PRIMARY KEY (fantasygameID));

CREATE TABLE PlayedIn
(playerID DECIMAL(10,0) NOT NULL,
 gameID DECIMAL(10,0) NOT NULL,
 goals INTEGER NOT NULL,
 catches INTEGER NOT NULL,
 assists INTEGER NOT NULL,
 completions INTEGER NOT NULL,
 blocks INTEGER NOT NULL,
 turnover INTEGER NOT NULL,
 PRIMARY KEY (playerID, gameID),
 FOREIGN KEY (playerID) REFERENCES Player(playerID),
 FOREIGN KEY (gameID) REFERENCES Game(gameID));

CREATE TABLE FantasyPlayedIn
(teamID DECIMAL(10,0) NOT NULL,
 fantasygameID DECIMAL(10,0) NOT NULL,
 won? BOOLEAN NOT NULL,
 score INTEGER[2] NOT NULL,
 PRIMARY KEY (teamID, fantasygameID),
 FOREIGN KEY (teamID) REFERENCES Team(teamID),
 FOREIGN KEY (fantasygameID) REFERENCES FantasyGame(fantasygameID));

CREATE TABLE IsOn
(playerID DECIMAL(10,0) NOT NULL,
 teamID DECIMAL(10,0) NOT NULL,
 PRIMARY KEY (playerID, teamID),
 FOREIGN KEY (playerID) REFERENCES Player(playerID),
 FOREIGN KEY (teamID) REFERENCES Team(teamID));

CREATE TABLE Owns
(userID DECIMAL(10,0) NOT NULL,
 teamID DECIMAL(10,0) NOT NULL,
 PRIMARY KEY (userID, teamID),
 FOREIGN KEY (userID) REFERENCES username(userID),
 FOREIGN KEY (teamID) REFERENCES Team(teamID));
