"""empty message

Revision ID: 56df3dca8056
Revises: 
Create Date: 2018-11-07 23:28:48.940589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56df3dca8056'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_table('AGENTS')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AGENTS',
    sa.Column('AGENT_CODE', sa.CHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('AGENT_NAME', sa.CHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('WORKING_AREA', sa.CHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('COMMISSION', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('PHONE_NO', sa.CHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('COUNTRY', sa.CHAR(length=25), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('AGENT_CODE', name='AGENTS_pkey')
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
